Dev
Romx98/MZK-scripts pull request #1
Opened 2021-06-08 09:28 UTC by Romx98

2021-06-09 15:30 UTC, kazooo requested changes

2021-06-09 15:30 UTC, kazooo commented on build.gradle
> +}
Přidej new line - https://gist.github.com/camh-/1bebfcff1b0f814e9b191edc60d5206b

2021-06-09 15:30 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/RestClient.java
> +    public RestClient(String fh, String fu, String fp)
Zkus jiný název, např. FedoraRestClient. Předpokládej, že budeš tohoto klienta znovu použivat v jiných skriptech, kde budou klienti pro Kramerius API, apod. Takže je potřeba dobrý název, podle kterého dokažeš těchto klientů rozlišit.

2021-06-09 15:30 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/RestClient.java
> +        xmlPathExp = xmlPath.compile("//*[local-name() = 'isMemberOfCollection']");
Pro parsování XML elementů bych udělal další pomocný servis. Těch XPathExpressions bude víc. Ale zatim at to zůstane takto.

2021-06-09 15:30 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/RestClient.java
> +        if (doc == null) { return null; }
Snaž se vyhnout jednořádkovým if výrazům. U složitějších výrazu pak může byt složitý debugging apod

2021-06-09 15:30 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/RestClient.java
> +        String uuidVC = getFullFormatVC(vc);
Nekontroluješ je-li vc null

2021-06-09 15:30 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/RestClient.java
> +            if (node.getAttributes().item(0).getTextContent().equals(uuidVC) ||
```suggestion
            if (node.getAttributes().item(0).getTextContent().equals(uuidVC) ||
```
node.getAttributes() může vratit prazdný list, a .item(0) vyhodí ArrayOutOfBoxException
Mimo jiné, musiš vybrat attribut "resources", který nemusí byt první.

2021-06-09 15:30 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/RestClient.java
> +                node.getAttributes().item(0).getTextContent().isEmpty()) {
Pokud uuidVc je prazdný String, tak bude true ještě v první podmince, takže tento výraz je zbytečný.

2021-06-09 15:30 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/RestClient.java
> +    public Document removeAllVC(Document doc, String vc) throws XPathExpressionException {
Název removeVc je trochu lepší podle mě, ale jak chceš, at to bude tak

2021-06-09 15:30 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/RestClient.java
> +        if (doc == null) { return; }
Viz komentář výše

2021-06-09 15:30 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/RestClient.java
> +        return null;
Nevracej null z funkcí, bad habbit. Koukni do Optional nebo vyhod výjimku.

2021-06-09 15:30 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/RunRestClient.java
> +public class RunRestClient {
Název trídy nic neříká, změn na nějaký RemoveVcFromFOXML, aby název mohl říct co skriptu dělá.

2021-06-09 15:30 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/RunRestClient.java
> +        System.out.println(restClient.docToStr(doc));
V docToStr nekontroluješ je-li doc null -> NullPointerException

2021-06-09 15:34 UTC, kazooo commented
Názvy PR a commitů mohou byt informativnější, stejně tak i popisy. Snaž se názvy a popisy psat v angličtině aby nebyl mix jázyků.

2021-06-10 13:02 UTC, Romx98 reviewed
Spravil som nejaké zmeny (pridal som Optional), čiže predpokladám, že by tam už nemal byť problém s return null; @kazooo

2021-06-11 13:17 UTC, kazooo commented
Prosím zapisuj commit message jako

```
<stručný shrnující popis změn>

<podrobnější popis změn>
```
aby se ti v GUI nezobrazoval dlouhý popis, který je nutne otevřit abys zjistil o co jde.
Například

```
Extend FedoraClient API

 - add new REST API endpoint blablabla
 - refactor method()
```
Pak budeš mit krasně formatované commity a bude to cool  :)

2021-06-11 14:03 UTC, kazooo requested changes
Oprav to co tady už máš a už neposilej nic nového, máme už velmi dlouhý log

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/FedoraRestClient.java
> +        //factory.setNamespaceAware(true);
Proč jsi to okomentoval?

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/FedoraRestClient.java
> +        if ((doc != null) && (vc != null)) {
Závorky kolem *doc* a *vc* jsou zbytečné, ale mohou byt

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/FedoraRestClient.java
> +            NodeList nodes = (NodeList) xmlPathExp.evaluate(doc, XPathConstants.NODESET);
Přejmenuj na attrubuteNodes, at tem název vic říká

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/FedoraRestClient.java
> +                Node node = nodes.item(i);
node může byt attrNode

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/FedoraRestClient.java
> +                    }
Toto celé můžeš udělat jako samostatnou funkci

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/FedoraRestClient.java
> +            throws IOException, TransformerException {
Na jeden řádek

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/FedoraRestClient.java
> +
Zbytečně

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/FedoraRestClient.java
> +
Zbytečně

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/FedoraRestClient.java
> +
Zbytečně

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/FedoraRestClient.java
> +    public Optional<String> docToStr(Document doc) throws TransformerException {
Když je to private funkce (asi by měla byt private), tak bych tady čekal, že předtím něž pošleš doc na konverzí, tak ho zkontroluješ, takže Optional není potřeba

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/FedoraRestClient.java
> +            throws IOException {
Na jeden řádek

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/FedoraRestClient.java
> +
Zbytečně

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/FedoraRestClient.java
> +
Zbytečně

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/RemoveVcFromFOXML.java
> +        //System.out.println(fedoraRestClient.docToStr(doc));
Okomentovaný kodu ideálně nemá byt v commitech

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/RemoveVcFromFOXML.java
> +            fedoraRestClient.setRelsExt(uuid, doc.get());
Ziskáváš full FOXML, a posíláš ho jako RELS-EXT, Fedora ti to neakceptuje. Zpracuj jen RELS-EXT, tady to bohatě stačí.

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/documentcorrection/RemoveVcFromFOXML.java
> +
Zbytečně

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/model/DataStreams.java
> +//
?

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/model/DataStreams.java
> +
Možná ne vždy to jde, ale snaž se mezi logickými bloky koda dodržovat pouze jeden řádek.

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/model/DataStreams.java
> +
Zbytečně

2021-06-11 14:03 UTC, kazooo commented on src/main/java/cz/mzk/fedora/model/DataStreams.java
> +
Zbytečně

2021-06-12 18:04 UTC, Romx98 commented on src/main/java/cz/mzk/fedora/documentcorrection/FedoraRestClient.java
> +        //factory.setNamespaceAware(true);
Mal som to odkomentovane, ked som pouzival XPath expression //*[local-name() = 'isMemberOfCollection'], lenze ked som skusil pouzit   //*[local-name() = 'isMemberOfCollection']/@resource tak mi to neslo... trosku som experimentoval a ked som to zakomentoval, tak mi to zrazu fungovalo

2021-06-17 07:14 UTC, merged